import type { NextPage } from 'next'
import Head from 'next/head'

import Colaborador from './Colaborador'
import Cargos from './Cargos';

interface AxiosProps {
  items: {
    agent_id: string;
    branch?: string;
    department: string;
    image: string;
    name: string;
    role: string;
    status: "active" | "inactive" | string;
  }[]
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pedido Pago | HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Colaborador />
        <Cargos />
      </main>
    </div>
  )
}

export default Home
